### ISSUE TITLE
NFR: Standard lorem ipsum

### ISSUE THREAD

**Issue by szegheo** [kstenschke/dummytext-plugin#3]
Hi! I've just installed the plugin, works great, but I really miss one simple thing:
An item called "Generate standard lorem ipsum" with the standard text:

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

Fake latin is great but difficult to use if you want to generate longer text into an empty area.
Could you please add this feature? I've zero knowledge in java programming :(

**Comment by kstenschke** [comment]
Hi Szegheo, thanks for your feedback! I might add an option for setting the initial length of new dummy text to be generated (when not replacing a selection). At the moment i recommend the following:

You can set the length of generated text, by selecting some text and than running the generator on it. This way the dummy text will be approximately as long as the original text, it replaces.
For a longer text of fake latin, you can simply insert some fake latin once, select it, duplicate the selection (CTRL+D, or CMD+D on Mac OS) until it's long enough, than select the whole block and evoke the dummy text generator once again: voilà - just the amount of fake latin you need.
