### ISSUE TITLE
Length of newly inserted text.

### ISSUE THREAD

**Issue by DigiLive** [kstenschke/dummytext-plugin#6]
When I insert a dummy text at the cursor (no selection) it only return one sentence which in my opinion is too short for the goal of inserting a dummy text.

I would like to see an setting for the length or maybe have an selection of empty lines be filled with dummy text. (Now the selected empty lines stay blank)

**Comment by Lightheaded** [comment]
+1

**Comment by CodeDMF** [comment]
+1

**Comment by grimseer** [comment]
+1

**Comment by mkwsra** [comment]
+1

**Comment by rp6** [comment]
+1

**Comment by mikevaleriano** [comment]
+1

**Comment by nelo112** [comment]
+1

**Comment by goodmind** [comment]
+1

**Comment by QuentinBrosse** [comment]
+1

**Comment by Andris91** [comment]
+1

**Comment by SOYOS** [comment]
+1

**Comment by ericmorand** [comment]
+1

**Comment by mkwsra** [comment]
Guys just use the IntelliJ IDEA/PHPStorm live templates.

There is a default one (or I added it long time ago?! I really don't recall)

Type `lorem` click `TAB` 😄  it's better than this plugin 😉

**Comment by robsch** [comment]
@mkwsra your right. But it's a feature of **emmet** what gets used. Doc is here: http://docs.emmet.io/abbreviations/lorem-ipsum/

I don't want to complain about free software, but the dummy text plugin is quite useless if it can only create a single line.

**Comment by kstenschke** [comment]
The idea behind the plugin was to allow quick alteration of templates. That is- replacing selections of text with generated dummy text of more or less the same length.
In other words (as stated in the plugin description): The setting for the length is: the amount of selected text when replacing, the fallback is 1 line.

For the time being you can generate e.g. 10 lines by: 
* generate 1 line, press ctrl+d (command+d on macs) with the caret on the line 9 times
* select the 10 lines, evoke the dummytext plugin again.

As so many people like the plugin (you can show your apreciation by starring the plugin on the jetbrains repository) and would like to see this feature, i'll try to find the time to add some sort of explicit setting for this.

**Comment by greaterking** [comment]
@robsch agreed. Thanks didn't know emmet had this. Also thank to the author as well...needed this for my templates.

**Comment by DigiLive** [comment]
This issue seems pretty much obsolete by now. Can be closet.

**Comment by c33s** [comment]
@DigiLive have i missed something, is this fixed? can't find a config dialog in version 1.2.0. 

@kstenschke it would be so awesome to have a config or a dialog for this so this addon is not just for replacing existing text but really generate new text.

https://www.blindtextgenerator.com/lorem-ipsum

![image](https://user-images.githubusercontent.com/649209/125780800-90ad57bd-0880-4285-b65f-12996407f4ce.png)
