### ISSUE TITLE
Support multiple selections

### ISSUE THREAD

**Issue by idontusenumbers** [kstenschke/dummytext-plugin#8]
File `dummytext-plugin/src/com/kstenschke/dummytext/ActionPerformer.java:~69`

seems to support only one selection. There's some sample code around multiple selections here:
https://www.jetbrains.org/intellij/sdk/docs/tutorials/editor_basics/working_with_text.html

and related code here:
https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/openapi/editor/EditorModificationUtil.java

**Comment by kstenschke** [comment]
thankyou for your suggestio.
please feel free to send a PR should you want to implement multi-selection handling.

**Comment by kstenschke** [comment]
@idontusenumbers Thanks again for your PR, i (finally) am preparing an update release, including your contribution. I took the liberty to list you as a contributor within the README ;-)
